server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/jpinh/Documents/Disciplinas_UFRN/PD/Unidade_III/support-triage-config
          default-label: main
          clone-on-start: true
          force-pull: true
          refresh-rate: 30   

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true